#!/bin/bash
#: Title		: Show EnCase Image Info
#: Date			: 08-07-2013
#: Author		: "Porter Olsen" polsen@umd.edu
#: Version		: 1.0
#: Description	: Shows meta data saved with the EnCase (E01) disk image
# by Porter Olsen (c) 2013

TITLE="EnCase Disk Image Info"

ewfinfo "$@" | \
	zenity --text-info \
		--title "EnCase Disk Image Info" \
		--width=640 \
		--height=480

exit 0
